"""
Django settings for tiendalibros project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5+ft=&&l(y&87^0j^djho3(lhs7lv7x3)68cju#(av^d-*jj6l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['django.secnot.com',]


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'easy_thumbnails',
    'isbn_field',
    'libros',
    'tiendalibros', # Para templates
    'pagos',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'tiendalibros.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tiendalibros.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'es_ES'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

SITE_ROOT = os.path.dirname(os.path.realpath('__file__'))

STATIC_URL = '/static/'
MEDIA_URL  = '/media/'

STATIC_ROOT = os.path.join(SITE_ROOT, 'static')
MEDIA_ROOT  = os.path.join(SITE_ROOT, 'media')

SITE_URL = 'http://django.secnot.com'

# Easy Thumbnails
THUMBNAIL_DEBUG = True
THUMBNAIL_BASEDIR = '_thumbs/'
THUMBNAIL_PREFIX = 'thumb_'
THUMBNAIL_ALIASES = {
    'libros.Libro': {
        'cover': {'size': (230, 345), 'crop': 'smart'},
        'small_cover': {'size': (120, 185), 'crop': 'smart'},
        'thumbnail': {'size': (90, 135), 'crop': 'smart'},
    },
    'libros.Autor': {
        'portrait': {'size': (210, 0),
                    'bw': True,
                    'upscale':True,},
    },
}

# Configuracion de paypal
PAYPAL_MODE = 'sandbox'
PAYPAL_CLIENT_ID = 'Introduce tu CLIENT_ID'
PAYPAL_CLIENT_SECRET = 'Introduce to CLIENT_SECRET'

# Configurara Mail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL  = 'tu@direccionemail.com'
SERVER_EMAIL        = 'tu@direccionemail.com'
EMAIL_USE_TLS       = True
EMAIL_HOST          = 'smtp.direccionemail.com'
EMAIL_PORT          = 587

EMAIL_HOST_USER     = 'usuario@direccionemail.com'
EMAIL_HOST_PASSWORD = 'claveservidor'
